version: 2

sources:
  - name: raw
    schema: dev_raw
    tables:
      - name: events
        identifier: raw_events

      - name: installs_attribution
        identifier: raw_installs_attribution_table

      - name: marketing_spend
        identifier: raw_marketing_spend_table

  - name: stg
    schema: dev_stg
    tables:
      - name: events
        identifier: stg_events
